name: "dbt_pov_model_cost_calculator_integration_tests"
version: "0.1.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "test_project"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Configures the target directory where dbt will materialize artifacts
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configure query comments to include comprehensive metadata
query-comment: "{{ dbt_pov_model_cost_calculator.query_comment(node) }}"

# Variables for the plugin
vars:
  # Schema where the tracking table will be created
  artifact_schema: "{{ target.schema }}"
  # Table name for tracking model executions
  artifact_table: "dbt_model_executions"
  # Batch size for inserting model execution records (default: 500)
  batch_size: 100
  # Start date for query monitoring (default: 7 days ago for testing)
  model_monitor_start_date: "{{ (modules.datetime.datetime.now() - modules.datetime.timedelta(days=7)).strftime('%Y-%m-%d') }}"

  # System table overrides (optional - defaults to standard system tables)
  databricks_query_history_table: "system.query.history"
  databricks_billing_usage_table: "system.billing.usage"
  databricks_billing_prices_table: "system.billing.list_prices"
  snowflake_query_history_table: "snowflake.account_usage.query_history"
  snowflake_query_attribution_table: "snowflake.account_usage.query_attribution_history"

models:
  test_project:
    # Config indicated by + and applies to all files under models/example/
    +materialized: view