version: 2

models:
  - name: model_queries
    description: "Model execution data joined with query history and cost information from the underlying data warehouse"
    schema: "{{ var('artifact_schema', target.schema) }}"
    materialized: view
    columns:
      - name: query_id
        description: "Unique identifier for the executed query from the data warehouse"
      - name: model_name
        description: "Name of the dbt model that was executed"
        tests:
          - not_null
      - name: model_package
        description: "Package name where the model is defined"
      - name: dbt_cloud_job_id
        description: "dbt Cloud job ID used to match queries"
      - name: dbt_cloud_run_id
        description: "dbt Cloud run ID used to match queries"
      - name: execution_time
        description: "Time taken to execute the model in seconds (from dbt)"
      - name: status
        description: "Execution status of the model"
      - name: invocation_id
        description: "Unique identifier for the dbt run invocation"
      - name: query_text
        description: "The actual SQL query text executed in the data warehouse"
      - name: estimated_cost_usd
        description: "Estimated cost of the query in USD based on data warehouse pricing"
